export const HttpResponse = {
  USER_ALREADY_EXIST: 'User already exists with this email.',
  OTP_SENT: 'OTP has been sent successfully.',
  OTP_STORING_FAILED: 'Failed to store OTP. Please try again.',
  INVALID_OTP: 'Invalid or expired OTP.',
  OTP_VERIFIED: 'OTP verified successfully.',
  OTP_RESENT: 'OTP has been resent.',
  USER_CREATED: 'User registered successfully.',
  INVALID_CREDENTIALS: 'Invalid email or password.',
  LOGIN_SUCCESS: 'Login successful.',
  USER_NOT_FOUND: 'User not found.',
  AUTH_SUCCESS: 'User authenticated successfully.',
  URL_CREATED: 'URL created successfully.',
  URL_FETCHED: 'URL fetched successfully.',
  URL_UPDATED: 'URL updated successfully.',
  URL_DELETED: 'URL deleted successfully.',
  URL_FOUND: 'URL found successfully.',
  URL_NOT_FOUND: 'URL not found.',
  URL_HISTORY_FOUND: 'URL history fetched successfully.',
};
